# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'An', url: 'an.html'}
- {name: 'Posts', url: 'posts.html'}
- {name: 'Research', url: 'research.html'}
- {name: 'Gallery',   url: 'gallery.html'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://github.com/D093gg'}
- {icon: 'envelope',   link: 'mailto:anlao2000@outlook.com'}
- {icon: 'weixin',     link: 'https://mp.weixin.qq.com/s/Yw_lEMUk2uijah9PgY-2Iw'}
- {icon: 'music',      link: 'https://music.163.com/#/artist?id=59780670'}
#- {icon: 'twitter',    link: ''}
#- {icon: 'linkedin',   link: ''}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
